### ISSUE TITLE
MLCT vs. LMCT performance for d4-d6 elements

### ISSUE THREAD

**Issue by Anselmoo** [mretegan/crispy#24]

**Comment by mretegan** [comment]
Hi Anselm,

Can you please tell more precisely what you want to calculate and what parameters are you using for the charge transfer term. Maybe send me the generated .lua file so I can have a look.

**Comment by Anselmoo** [comment]
Hi Marius,

I am on a trip, on Monday, I will send to you! Thank you very much! It’s a very nice interface with some very cool options. I love it and we are forced to use it …
Have a happy Monday … and best

Anselm

On 9. Sep 2019, at 09:37, Marius Retegan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Anselm,

Can you please tell more precisely what you want to calculate and what parameters are you using for the charge transfer term. Maybe send me the generated .lua file so I can have a look.
