### ISSUE TITLE
Bug check relating to B operator

### ISSUE THREAD

**Issue by mpmdean** [mretegan/crispy#3]
I recently created a lua script to compute 2p3d RIXS of a tetragonal Cu 2+ ion. 

This appeared to only include the B field operator in initial and intermediate states and not in the final state. 

i.e. it had
H_i = H_i + B
H_m = H_m + B

and not 
H_i = H_i + B
H_m = H_m + B
H_f = H_f + B

I was expecting the latter behavior.

**Comment by mretegan** [comment]
These templates are so easy to get wrong :disappointed: ... Fixed in 0a053b42b699c34a361f60e66d85b96d42cc49b1.
