### ISSUE TITLE
Wrong number of electrons in RIXS MLCT

### ISSUE THREAD

**Issue by mretegan** [mretegan/crispy#34]
The number of electrons is set to 10, but in this case, it should be 0.

**Comment by mretegan** [comment]
This is fixed in the latest release.

**Comment by VictorPoreeFr** [comment]
The line:
"H_3d_ligands_hybridization_mlct = 1/0"
is also missing when exporting the config file.
Once added it still behaves like it is not taking it into account:
N_L2 of the ground state remains 0 whereas it is non-zero when doing it in the XAS setting. I could not find any other missing line or wrong input.

**Comment by mretegan** [comment]
Fixed in version 0.8.0.
