### ISSUE TITLE
Python Import Crispy Function

### ISSUE THREAD

**Issue by WilliamJudge94** [mretegan/crispy#37]
Is there a way to import the main crispy simulation function into python? 

Example:
from crispy import simulation_function
spectra = simulation_function(param1, param2, param3, ...)

This would make it easier to iterate through parameters for a given spectrum.

**Comment by mretegan** [comment]
In the last version, there is such an interface. I've described it in my talk https://youtu.be/ovdLJXIqMEE?t=1123.

Note that at the moment it is **very** basic, but you should be able to use it to loop over parameters.
