### ISSUE TITLE
Bug check relating to partition function

### ISSUE THREAD

**Issue by mpmdean** [mretegan/crispy#4]
In the quanty.lua file created by crispy, it appears to sum over all initial states that have dZ < 1e-8 where dZ = math.exp(-(E - E_gs) / T). I think each spectrum should be weighted by dZ before summing. Please can this be checked? 

I think think the code needs 
spectrum = spectrum + dZ * CreateResonantSpectra(...
near the end of the lua file. 

for j, OperatorOut in ipairs({Tx_3d_2p, Ty_3d_2p, Tz_3d_2p}) do
    for k, OperatorIn in ipairs({Tx_2p_3d, Ty_2p_3d, Tz_2p_3d}) do
        spectrum = 0
        Z = 0
        for i, Psi in ipairs(Psis) do
            E = Psi * H_i * Psi
            if math.abs(E - E_gs) < 1e-12 then
                dZ = 1
            else
                dZ = math.exp(-(E - E_gs) / T)
            end
            if (dZ < 1e-8) then
                print(string.format("Stop after %i spectra were computed\n", i))
                break
            end
            Z = Z + dZ
            spectrum = spectrum + dZ * CreateResonantSpectra(H_m, H_f, OperatorIn, OperatorOut, Psi, {{'Emin1', Emin1}, {'Emax1', Emax1}, {'NE1', NE1}, {'Gamma1', Gamma1}, {'Emin2', Emin2}, {'Emax2', Emax2}, {'NE2', NE2}, {'Gamma2', Gamma2}})
        end
        spectrum = spectrum / Z
        spectrum.Print({{'file', 'RIXS_pol_' .. j .. k .. '_out.spec'}})
    end
end

**Comment by mretegan** [comment]
Indeed in the case of the RIXS templates the weighting of the individual spectra was not done. This is now fixed in 2b9c81dee5eeea75cbb80610b189543fc29100f4.
