### ISSUE TITLE
crispy-plotting

### ISSUE THREAD

**Issue by mahendra-147** [mretegan/crispy#43]
Dear Dr Marius.S.Retegen,

                 This is regarding the interface you developed 'Crispy'.  
I have installed it on Ubuntu 20.4 LTE via pip3.
Installation went well and the program runs smoothly.
The background engine 'Quanty' also got recognized.
But plotting is not happening.

Please let me know where to look for?

Mahendra

**Comment by mretegan** [comment]
@mahendra-147 

It is very hard to debug this. You could try saving the input file to your home folder using the "Save Input As..." button and then run the calculation.
