### ISSUE TITLE
Notebook calc.run() Error

### ISSUE THREAD

**Issue by WilliamJudge94** [mretegan/crispy#45]
After following the notebook tutorial found at https://www.youtube.com/watch?t=1123&v=ovdLJXIqMEE&feature=youtu.be, I was unable to run the command calc.run(). I received the error in the attached image.

Crispy Version = 2020.1rc0
Python Version == 3.7 

<img width="1028" alt="Screen Shot 2021-01-21 at 12 27 35 PM" src="https://user-images.githubusercontent.com/37912237/105387984-181a9b00-5be4-11eb-9a93-4826ce5829ff.png">

**Comment by WilliamJudge94** [comment]
I believe the issue lies with crispy.config.Config.loadDefaults() never gets called inside the crispy.gui.quanty.calculation.Calculation() function. This is where you initially set the "CurrentPath" to os.path.expanduser("~")

crispy.gui.quanty.calculation.Calculation() is the main function of crispy.notebook.calculation. Because loadDefaults() is never called, this leaves settings.value("CurrentPath")=None. 

I am unsure if this is the full extent of the problem, but I figured I would leave a comment on what I learned from looking at the code.

**Comment by WilliamJudge94** [comment]
This is exactly the issue. I got the notebook version of crispy working by doing the following:

1) adding this bit of code after "settings = Config().read()" in crispy.gui.quanty.calculations.py


```python
settings.beginGroup("Quanty")
settings.setValue("Verbosity", "0x0000")
settings.setValue("DenseBorder", "2000")
settings.setValue("RemoveFiles", True)
settings.endGroup()
```


2) adding this bit of code to the same file, but farther down. To be placed in the already defined function executablePath(self): THIS IS NOT THE WHOLE FUNCTION. Just an example of what to add right at the beginning of the function.

```python
def executablePath(self):
    path = Config().read().value("Quanty/Path")
    path = '/path/to/Quanty'`
```

**Comment by mretegan** [comment]
@WilliamJudge94 thanks for the having a look at this. The problem was indeed related to "settings.ini" not being created. I've pushed some changes to the code, and it should all work now.
