### ISSUE TITLE
Crispy Not Working

### ISSUE THREAD

**Issue by WilliamJudge94** [mretegan/crispy#51]
I have tried to install Crispy onto a new machine. Both the GUI and the Notebook versions.

No matter what I do I am unable to get either version to calculate spectra.

My steps to install:

1. Create a new conda env `conda create -n crisp python=3.7`
2. activate env `source activate crisp`
3. install env to jupyter `pip install ipykernel` `ipython kernel install --user --name=crisp`
4. install slix `pip install slix[full]`
5. install crispy `pip3 install --upgrade crispy==2020.1rc0` (the only version that I have gotten close to working with Notebooks
6. download Quanty from their website
7. make Quanty executable `chmod 777 Quanty`
8. set Quanty path in GUI by using the GUI
9. set Quanty path in scripts by `path` variable in `/crispy/gui/quanty/calculations.py - def executablePath function` to the path of Quanty

I cannot seem to get any simulation results. And when using the GUI, after I hit run the only thing the program shows is `Quanty has stopped`

**Comment by WilliamJudge94** [comment]
System -

Ubuntu 20.04
CPU - Threadripper Pro
GPU - Nvidia P2200

**Comment by WilliamJudge94** [comment]
After running Quanty separately with the crispy generated .lua file I was able to get an error code of `Illegal instruction (core dumped)`. I am unsure if this is an Ubuntu 20.04 issue or a Threadripper Pro issue.

**Comment by mretegan** [comment]
@WilliamJudge94 Could you please me the Lua file?

**Comment by WilliamJudge94** [comment]
1) Github wouldn't let me upload the .lua file as it. I had to change the extension to .txt to upload it.
2) The attached file runs perfectly fine on an AMD 1700x or an old Intel Core Duo. No issues at all. But if I:
    a) either download a new Quanty or Move the AMD 1700x machine's Quanty to the AMD Threadripper Pro
    b) use the exact same .lua file on both AMD 1700x and AMD Threadripper Pro

The AMD Threadripper Pro still errors out with "Illegal Instruction (core dumped)"

[Ni2+_Oh_XAS_2p.txt](https://github.com/mretegan/crispy/files/6742290/Ni2%2B_Oh_XAS_2p.txt)

**Comment by mretegan** [comment]
The issue might be with the way Quanty is compiled. I will try to find an AMD machine to make a new binary.

**Comment by WilliamJudge94** [comment]
If you would like I can try to compile the binary on my AMD Threadripper Pro to see if that fixes the issue? Then send back the new binary file.

**Comment by mretegan** [comment]
@WilliamJudge94 I've compiled Quanty on an AMD EPYC machine. Could you please try with the binary from this page https://cloud.esrf.fr/s/z944SgTtZZtkm3x.

**Comment by WilliamJudge94** [comment]
This worked!!! Thank you so much!

**Comment by WilliamJudge94** [comment]
As a small side note to anyone else trying to use this version of Quanty. You must first change the file permissions by running `chmod -R 777 Quanty` inside the directory where Quanty was saved.

**Comment by mretegan** [comment]
@WilliamJudge94 Glad to hear it worked. For the next release, I will do a few tests to make sure that the version included in the package is compatible with more recent platforms.
